[buildPlans.Jet]
family = "Jet"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Jet.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
capital-i = "short-serifed"
capital-q = "straight"
f = "serifless"
g = "single-storey-flat-hook-serifless"
t = "bent-hook"
asterisk = "penta-high"
ampersand = "upper-open"
at = "compact"
question = "corner-flat-hooked"

[buildPlans.Jet.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Jet.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Jet.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Jet.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Jet.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Jet.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Jet.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
